<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function permitted ($user, $permission)
    {
        $return = false;
        
        $user           = $this->findOneBy(array("id" => $user));
        $profile        = $user->getProfile();
        $permissions    = $profile->getPermissionS();
        $permitted      = false;
        
        foreach ($permissions as $aPermission) {
            $equal = ($permission == $aPermission->getUrl());
            
            if ($equal) {
                $return = true;
                break;
            }
        }
        
        return $return;
    }

    public function getUserByEmailPassword ($email, $password)
    {
        $password   = md5($password);
        $user       = $this->findOneBy(array("email" => $email,"password"=>$password));
        
        return $user;
    }
}